dist: trusty

sudo: required

language: go

os:
    - linux

go:
  - 1.9.1
  - 1.10.1
  - 1.11.1
  - tip

matrix:
  allow_failures:
  - go: tip
            
script:
  - ./lint.sh
  - ./build.sh
  - ./test.sh

